---
# Käsitsi eemaldamise käsud:
# sudo apt remove php8.2 php8.2-cli php8.2-common php8.2-fpm -y
# sudo apt purge php8.2* -y
# sudo apt autoremove -y
# php -v

- name: Eemalda PHP 8.2 kliendiserveritest
  hosts: webservers
  become: yes

  tasks:
    - name: Eemalda PHP 8.2 paketid
      apt:
        name:
          - php8.2
          - php8.2-cli
          - php8.2-common
          - php8.2-fpm
        state: absent
        purge: yes
        autoremove: yes
      when: ansible_distribution == "Debian"

    - name: Kontrolli kas PHP on alles
      command: php -v
      register: php_check
      ignore_errors: yes
      when: ansible_distribution == "Debian"

    - name: Kuva kontrolli tulemus
      debug:
        var: php_check.stderr
      when: ansible_distribution == "Debian"
